Issue 261 custom writer for progress spinners
pterm/pterm pull request #337
Opened 2022-04-02 16:55 UTC by Brookke

### Description
Adds a custom writer to the progress bar and spinner components.

### Scope
> What is affected by this pull request?
ProgressBar and Spinner

- [ ] Bug Fix
- [x] New Feature
- [ ] Documentation
- [ ] Other

### Related Issue
Fixes #261 

### To-Do Checklist
- [ ] I tested my changes
- [x] I have commented every method that I created/changed
- [ ] I updated the examples to fit with my changes
- [x] I have added tests for my newly created methods

2022-04-02 16:56 UTC, Brookke commented on docs/docs/printer/progressbar.md
> -|[UpdateTitle(title string)](https://pkg.go.dev/github.com/pterm/pterm#TemplatePrinter.UpdateTitle)|Update the progressbar's title.|
These links seemed wrong so I updated them too :)

2022-04-05 17:01 UTC, lowdewijk commented
Exactly what I need! Was actually considering doing this myself. 👍

2022-04-05 22:57 UTC, MarvinJWendt commented
Hi @Brookke, thanks for the PR! Could you maybe add some tests to ensure, the output is actually written to the given writer? You can do that with testza: https://github.com/MarvinJWendt/testza#capturestderr

You could use the writer in the callback function to write to and assert the output contains a word you put into the progressbar / spinner title. Thanks!

2022-04-10 23:42 UTC, MarvinJWendt requested changes
Some more unit tests, that capture the output and ensure that a specific writer is used, are missing. If you need help with testza, just ping me here or on Discord :)

2022-04-11 10:00 UTC, Brookke commented
@MarvinJWendt I have added some tests for the spinner printer, and I will do the same for the progress bar soon. However I had to add time.sleeps in order to wait for the go routines to run, which isn't great. If you have any other suggestions do let me know

2022-04-11 10:02 UTC, Brookke commented
Additionally it looks like the tests fail on ubuntu, I will investigate why

2022-04-12 11:15 UTC, MarvinJWendt commented
> @MarvinJWendt I have added some tests for the spinner printer, and I will do the same for the progress bar soon. However I had to add time.sleeps in order to wait for the go routines to run, which isn't great. If you have any other suggestions do let me know

The CI-System takes ages to complete already, so I don't think the second delay is a problem, as I also can't think of an easy solution.

2022-04-12 18:47 UTC, Brookke commented
@MarvinJWendt great thanks, I'll do the same for the progress back early next week, currently on holiday :)

2022-04-20 21:11 UTC, MarvinJWendt approved these changes
I hope you enjoyed your holidays! The PR looks good to me!

2022-04-20 21:11 UTC, merged