Customizable multiselect printer
pterm/pterm pull request #402
Opened 2022-09-09 12:13 UTC by jochil

### Description
Adding options to the `InteractiveMultiselectPrinter` to customize it:

- `NoFilter` to disable fuzzy search / filter
- `KeySelect` and `KeyConfirm` to use custom keys for selecting an item and confirm selection 

### Scope
> What is affected by this pull request?

- [ ] Bug Fix
- [X] New Feature
- [X] Documentation
- [ ] Other

### Related Issue
Fixes #

### To-Do Checklist
- [X] I tested my changes
- [X] I have commented every method that I created/changed
- [X] I updated the examples to fit with my changes
- [ ] I have added tests for my newly created methods

2022-09-10 11:24 UTC, MarvinJWendt commented
Thanks for the PR! I'll take a look soon 👍

2022-09-12 12:40 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +		return nil, fmt.Errorf("if filter/search is active, keys.Space can not use for KeySelect or KeyConfirm")
```suggestion
		return nil, fmt.Errorf("if filter/search is active, keys.Space can not be used for KeySelect or KeyConfirm")
```

2022-09-12 12:48 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +		KeyConfirm:     keys.Tab,
The methods `WithKeySelect` and `WithKeyConfirm` are missing 😉

2022-09-12 12:54 UTC, MarvinJWendt requested changes

2022-09-12 12:54 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +	NoFilter       bool
Could this variable name be changed to `Filter` and be true by default?

2022-09-12 12:54 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +func (p InteractiveMultiselectPrinter) WithNoFilter() *InteractiveMultiselectPrinter {
Could this be changed to `WithFilter`. Users could disable it with `WithFilter(false)` then.
In PTerm we usually just enable options by default with the `WithXxx` methods. For disabling, we use the approach above :)

2022-09-12 12:55 UTC, MarvinJWendt commented
Hi @jochil, I have left some comments, the rest looks good! I'll merge it when you've fixed the comments 🚀

2022-09-12 15:07 UTC, jochil commented
> Hi @jochil, I have left some comments, the rest looks good! I'll merge it when you've fixed the comments rocket

Thanks for the feedback... I fixed the comments

2022-09-29 18:41 UTC, jochil commented
@MarvinJWendt Hi. Is there something else I can adjust, please let me know :)

2022-10-01 22:56 UTC, MarvinJWendt commented
Hi @jochil, sorry for the long wait, I will review it now :)

2022-10-01 23:07 UTC, MarvinJWendt approved these changes
I just renamed the example. Thanks for the PR, and sorry for the delay. LGTM! 🚀

2022-10-01 23:08 UTC, merged