add: proposal option to change checkmarks in the intercactive multise…
pterm/pterm pull request #429
Opened 2023-01-03 23:49 UTC by KarolosLykos

### Description
Added the option to define the checkmarks in the interactive multiselect printer.
Also added some basic test cases.

### Scope
> What is affected by this pull request?

- [ ] Bug Fix
- [x] New Feature
- [x] Documentation
- [x] Other

### Related Issue
Fixes #418

### To-Do Checklist
- [x] I tested my changes
- [x] I have commented every method that I created/changed
- [x] I updated the examples to fit with my changes
- [x] I have added tests for my newly created methods

2023-01-04 22:14 UTC, MarvinJWendt requested changes
Thanks for the PR, really appreciate it. Just some nitpicking stuff, otherwise it looks good 👍

2023-01-04 22:14 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +
Could you please rename this to `Checkmark` (singular) and put it into the file `/atoms.go`, it's dedicated to those small helper structs :)

2023-01-04 22:14 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +func (p InteractiveMultiselectPrinter) WithCheckmarks(checkmarks Checkmarks) *InteractiveMultiselectPrinter {
This should then be `WithCheckmark`

2023-01-04 22:14 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +	NotSelected string
Please rename those to `Checked` and `Unchecked`.

2023-01-04 22:14 UTC, MarvinJWendt commented on interactive_multiselect_printer.go
> +	Checkmarks     Checkmarks
This should also be `Checkmark` then.

2023-01-04 22:14 UTC, MarvinJWendt commented on interactive_multiselect_printer_test.go
> +func TestInteractiveMultiselectPrinter_Show(t *testing.T) {
Thanks for adding tests! We somehow totally missed that for this printer @floaust 😅

2023-01-05 03:42 UTC, MarvinJWendt approved these changes
LGTM! Thanks for contributing 🎉 🚀

2023-01-05 03:44 UTC, merged

2023-01-05 03:57 UTC, MarvinJWendt commented
I have made some additional changes to enable changing the checkmarks via a custom theme. Should be pushed soon. :)

2023-01-05 10:25 UTC, KarolosLykos commented
> I have made some additional changes to enable changing the checkmarks via a custom theme. Should be pushed soon.

Yes, I was thinking adding that myself. That's great!!!