- add message_printer
pterm/pterm pull request #53
Opened 2020-10-15 19:00 UTC by suramrit

- add message_printer
- update spinner.go with message printer
- update spinner example

### Description
Still a work in Progress ‼️ 
PR is to get design reviewed. 👀  

added message_printer.go which allows 2 things - 
- Print a text to the console
- Print a text with defined style to the console

current issues - 
- for console output used "fmt" package. Alternative was "bufio", but not sure if that was necessary 
- in the working _example->spanner. Text is output with an additional newline still check why thats the case.  

### Scope
> What is affected by this pull request?

- [x] New Feature

### Related Issue
Refers #45

2020-10-15 19:13 UTC, MarvinJWendt requested changes
Hey, thanks for contributing. I have marked some stuff for you :)

2020-10-15 19:13 UTC, MarvinJWendt commented on _examples/spinner/main.go
>  func main() {
Please don't modify this file :)

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +type MessagePrinter struct {
Could you rename this to `BasicTextPrinter`

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +	Fatal bool
The `BasicTextPrinter` does not have to implement Fatal. Style is enough 😄

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +func (p MessagePrinter) WithFatal(b ...bool) *MessagePrinter {
This is also obsolete.

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +func (p MessagePrinter) Sprintf(format string, a ...interface{}) string {
Please use the function as described in the `CONTRIBUTING.md` file. You do not need to modify it. You only need to modify Sprint.

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +func (p MessagePrinter) Print(a ...interface{}) TextPrinter {
Please use the function as described in the `CONTRIBUTING.md` file. You do not need to modify it. You only need to modify Sprint.

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +func (p MessagePrinter) Println(a ...interface{}) TextPrinter {
Please use the function as described in the `CONTRIBUTING.md` file. You do not need to modify it. You only need to modify Sprint.

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +func (p MessagePrinter) Printf(format string, a ...interface{}) TextPrinter {
Please use the function as described in the `CONTRIBUTING.md` file. You do not need to modify it. You only need to modify Sprint.

2020-10-15 19:13 UTC, MarvinJWendt commented on spinner.go
> +	MessagePrinter: MessageVanilla,
Please leave this file unchanged :)

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +	return p.Style.Sprint(a...)
This is right, but you don't need the Style nil check. If the Style is nil, it will automatically print with normal text.

2020-10-15 19:13 UTC, MarvinJWendt commented on message_printer.go
> +	MessageVanilla = MessagePrinter{
Please refactor this to `DefaultBasic`. Style must not be set.

2020-10-15 19:24 UTC, suramrit commented
Thank you for the suggestions! @MarvinJWendt  
Ill refactor the code as you mentioned. 
For the example , I'll add a separate folder for BasicTextPrinter.

2020-10-18 14:44 UTC, MarvinJWendt approved these changes
LGTM! Thank you for contributing 😄

2020-10-18 14:44 UTC, merged