feat: add filter option for `select`
pterm/pterm pull request #530
Opened 2023-06-30 22:42 UTC by alirezaarzehgar

### Description
We have Filter option for multiselect printer but this feature is not available for select printer.
This PR implemented filter option for select printer.

### Scope
> What is affected by this pull request?

- [ ] Bug Fix
- [x] New Feature
- [ ] Documentation
- [ ] Other

### To-Do Checklist
- [x] I tested my changes
- [x] I have commented every method that I created/changed
- [ ] I updated the examples to fit with my changes
- [x] I have added tests for my newly created methods

2023-07-01 11:13 UTC, MarvinJWendt commented
Hi @alirezaarzehgar, thanks for the PR! Could you please merge `master` into this PR, and solve the conflicts? This should also fix the failed check, as we switched something in our CI System that was faulty.

2023-07-01 13:31 UTC, MarvinJWendt requested changes
Hi, looks good to me, only one thing that I noted below. You can use the web editor to merge the suggestion, if you want to.

2023-07-01 13:31 UTC, MarvinJWendt commented on interactive_select_printer.go
> +}
```suggestion
func (p InteractiveSelectPrinter) WithFilter(b ...bool) *InteractiveSelectPrinter {
	p.Filter = internal.WithBoolean(b)
	return &p
}
```

2023-07-02 11:48 UTC, alirezaarzehgar commented
> Hi, looks good to me, only one thing that I noted below. You can use the web editor to merge the suggestion, if you want to.

Hello. Done. I accepted your recommendation and resolve conflicts for now.

2023-07-03 00:11 UTC, MarvinJWendt approved these changes
LGTM! Thanks for contributing 🚀

2023-07-03 00:12 UTC, merged